# Generated by Django 2.2.6 on 2019-11-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_profiles', '0002_auto_20191108_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
