# Generated by Django 2.2.6 on 2019-11-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_profiles', '0002_auto_20191106_1111'),
        ('private_profiles', '0003_auto_20191108_0858'),
    ]

    operations = [
    ]
