# Generated by Django 2.2.5 on 2019-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_profiles', '0004_merge_20191108_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
