# Generated by Django 2.2.5 on 2019-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_profiles', '0004_merge_20191108_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='programming_languages',
            field=models.CharField(choices=[('Python', 'Python'), ('Ruby', 'Ruby'), ('Go(lang)', 'Go(lang)'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('PHP', 'PHP')], max_length=4, null=True),
        ),
    ]
